#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Запускаем lint-staged (линтинг и форматирование)
npx lint-staged

# Проверка типов TypeScript
npm run type-check

# Запуск тестов (закомментировано, включить при необходимости)
# npm run test

# Проверка на наличие уязвимостей в зависимостях
# npm audit --production 